/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.mycompany.project_team_14;

/**
 *
 * @author siddh
 */
public class TicketClerk {
    public String Name;
    public String Location;

    public void ReserveSeat() {
        System.out.println("Clerk " + Name + " is reserving a seat.");
    }

    public void ReserveTicket() {
        System.out.println("Ticket generated by clerk.");
    }

    public void CancelTicket() {
        System.out.println("Ticket cancelled by clerk.");
    }

    // Spelling 'Reseive' kept to match the class diagram provided
    public void ReseivePayment() {
        System.out.println("Payment received at " + Location);
    }
}
